### ISSUE TITLE
Full line of comments parsed as an `operator_identifier`

### ISSUE THREAD

**Issue by ckipp01** [tree-sitter/tree-sitter-scala#133]
Maybe an odd use case but I have a code base with comments like:

```
//////////////////
// MAIN MODULES //
//////////////////
```

And this ends up parsing as:

```
operator_identifier [24, 6] - [24, 27]
comment [25, 6] - [25, 27]
operator_identifier [26, 6] - [26, 27]
```

When it should really just be 3 comments.

**Comment by eed3si9n** [comment]
It seems like it requires some code around it like:

```scala
val = x

/////////////////////
// Foo             //
/////////////////////
```

then `/////////////////////` gets highlighted as an operator.

**Comment by eed3si9n** [comment]
Here's my PR for this - https://github.com/tree-sitter/tree-sitter-scala/pull/140
