### ISSUE TITLE
Change the way `interpolation` is modeled.

### ISSUE THREAD

**Issue by ckipp01** [tree-sitter/tree-sitter-scala#14]
I wonder if the `string_transform_expression` may be better named as `processed_string_expressions`. It also seems that the parsing now always just thinks that a `$` in a literal string is interpolation, which in incorrect. According to the [spec](https://scala-lang.org/files/archive/spec/2.13/01-lexical-syntax.html#string-literals):

> Interpolated string consist of an identifier starting with a letter immediately followed by a string literal.

We also don't actually have any tests in corpus covering `string_transform_expression`. With the way current things are, the following would parse like so:

```
==========================
Interpolated string
==========================

val stringLiteral = "$a"
---

(compilation_unit
  (val_definition (identifier)
    (string (interpolation (identifier)))))
```

When in reality, I think this should just be:

```
==========================
Interpolated string
==========================

val stringLiteral = "$a"
---

(compilation_unit
  (val_definition (identifier) (string)))
```

Currently with the `string_transorm_expression` you'll see the following:

```
==========================
Interpolated string
==========================

val stringLiteral = s"$a"
---

(compilation_unit
  (val_definition (identifier)
    (string_transform_expression (identifier)
      (string (interpolation (identifier))))))
```

So this is correct if `string_transform_expression` is indeed the term we want to go for, but I sort of feel that having the following may be clearer:

```
==========================
Interpolated string
==========================

val stringLiteral = s"$a"
---

(compilation_unit
  (val_definition (identifier)
    (processed_string_expression (identifier)
      (string (interpolation (identifier))))))
```

The processed language comes from this [SIP](https://docs.scala-lang.org/sips/string-interpolation.html), and you can see this referenced in the [string interpolation](https://docs.scala-lang.org/overviews/core/string-interpolation.html) section of the docs as well.

> In the above, the literal s"Hello, $name" is a processed string literal. This means that the compiler does some additional work to this literal. A processed string literal is denoted by a set of characters preceding the ".

**Comment by maxbrunsfeld** [comment]
This all sounds good. Do you want to open a PR with this change?
