### ISSUE TITLE
Feature request: support user-directives.

### ISSUE THREAD

**Issue by rochala** [tree-sitter/tree-sitter-scala#189]
With Scala-CLI probably becoming the default Scala driver, I think adding support for using directives is an important feature to have. The main benefit would most likely be highlighting.

**Comment by ckipp01** [comment]
Thanks @rochala! I have actually been thinking the same thing, especially since I've seen that the VS Code syntax supports it as well.

**Comment by susliko** [comment]
Was implemented in https://github.com/tree-sitter/tree-sitter-scala/pull/273
