### ISSUE TITLE
For comprehensions and loops

### ISSUE THREAD

**Issue by ckipp01** [tree-sitter/tree-sitter-scala#19]
One of the missing expressions is [for comprehensions and loops](https://www.scala-lang.org/files/archive/spec/2.13/06-expressions.html#for-comprehensions-and-for-loops).

For a very basic for loop I was thinking along the lines of something like this:

```
===============================
For comprehensions and for loops
===============================

object Main {
  val myList = List(1,2,3)
  for (x <- myList)
    yield x
}

---

(object_definition
  (identifier)
  (template_body
    (val_definition
      (identifier)
      (call_expression (identifier) (arguments (number) (number) (number)))
      (for_expression (enumerators
        (generator (identifier) (rhs))
        (yield_expression (identifier)))))))
```

However there are more things to think about in for comprehensions

- [ ] guards
- [ ] value definitions
- [ ] blocks (both enumerator and yield blocks)

There is probably more that I'm forgetting so I'll continue to just add to this as I play around with the corpus.

**Comment by stumash** [comment]
https://github.com/tree-sitter/tree-sitter-scala/pull/30

**Comment by maxbrunsfeld** [comment]
Nice work @stumash .
