### ISSUE TITLE
Match types

### ISSUE THREAD

**Issue by susliko** [tree-sitter/tree-sitter-scala#205]
### Commit of tree-sitter-scala you tested this on

7d348f5

### A code sample showing the error

```scala
object MatchTypes {
  type Elem[X] = X match
    case String => Char
}
```

### Show the error node

```
    ERROR [1, 2] - [2, 8]
      type_definition [1, 2] - [1, 18]
        name: type_identifier [1, 7] - [1, 11]
        type_parameters: type_parameters [1, 11] - [1, 14]
          name: identifier [1, 12] - [1, 13]
        type: type_identifier [1, 17] - [1, 18]
    self_type [2, 9] - [2, 18]
      identifier [2, 9] - [2, 15]
    identifier [2, 19] - [2, 23]
```

### What do you expect the tree to look like

I'd expect `match` in type definition to be handled 

### Where are you experiencing this error?

nvim-treesitter

**Comment by eed3si9n** [comment]
Here's my PR for this - https://github.com/tree-sitter/tree-sitter-scala/pull/244
