### ISSUE TITLE
To release or not to release

### ISSUE THREAD

**Issue by ghostbuster91** [tree-sitter/tree-sitter-scala#216]
Hi, 

Last gh release has been made almost a year ago - https://github.com/tree-sitter/tree-sitter-scala/releases/tag/v0.19.1 .

I would like to get some clarity regarding the "release" model. Is it planned to get back to doing regular releases or should people just use head/master?

Context:
In nixpkgs repository we have a script that updates grammars semi-automatically. It uses releases if at least one release has been made, otherwise it uses head/master. I can obviously change it to force use of head/master for scala but first I would like to get some confirmation that this is indeed the way forward. 

Cheers,

**Comment by ckipp01** [comment]
I don't think we've had a specific strategy here. Most of us are using it just with nvim, which pulls in the latest changes from head. WIth that being said if new releases are necessary after a chunk of changes, we can totally do that as well.

**Comment by ghostbuster91** [comment]
If that is not a problem, it would be my preference as that would mean that no changes to the nixpkgs update-script are necessary.

**Comment by eed3si9n** [comment]
My proposal would be to release `0.minor.patch` where:
1. `minor` matches the minor version of tree-sitter (currently `20`)
2. `patch` starts with `0`, and increments each time
3. Try to release something every 2 ~ 4 weeks, while the project is active

**Comment by eed3si9n** [comment]
0.20.0 is out.

- https://github.com/tree-sitter/tree-sitter-scala/releases/tag/v0.20.0
- https://eed3si9n.com/tree-sitter-scala-0.20.0

Feel free to open a new issue to get a release out.
