### ISSUE TITLE
Pattern declaration/definition of val/var

### ISSUE THREAD

**Issue by eed3si9n** [tree-sitter/tree-sitter-scala#253]
### Commit of tree-sitter-scala you tested this on

5a6fcbdddd015169f148d916e246e8faf90cc940

### A code sample showing the error

```scala
val res1, res2 = ArrayBuilder.make[A]
```

### Show the error node

```
scala/collection/ArrayOps.scala	8 ms	(ERROR [1486, 9] - [1486, 14])
```

### Where are you experiencing this error?

smoke test

**Comment by susliko** [comment]
Didn't even know it was a valid Scala syntax, lol

**Comment by eed3si9n** [comment]
Here's my PR for this -https://github.com/tree-sitter/tree-sitter-scala/pull/254
