### ISSUE TITLE
Refined types

### ISSUE THREAD

**Issue by susliko** [tree-sitter/tree-sitter-scala#265]
### Commit of tree-sitter-scala you tested this on

374709c

### A code sample showing the error

```scala
class A
object A:
  val a: A {
    val b: Int
  } = ???
```

### Show the error node

```
(compilation_unit [0, 0] - [5, 0]
  (class_definition [0, 0] - [0, 7]
    name: (identifier [0, 6] - [0, 7]))
  (object_definition [1, 0] - [5, 0]
    name: (identifier [1, 7] - [1, 8])
    body: (template_body [1, 8] - [5, 0]
      (val_definition [2, 2] - [4, 9]
        pattern: (identifier [2, 6] - [2, 7])
        (ERROR [2, 9] - [2, 10])
        type: (structural_type [2, 11] - [4, 3]
          (val_declaration [3, 4] - [3, 14]
            name: (identifier [3, 8] - [3, 9])
            type: (type_identifier [3, 11] - [3, 14])))
        value: (operator_identifier [4, 6] - [4, 9])))))
```

### Where are you experiencing this error?

Lots of code in scala compiler, [ClassfileParser.scala](https://github.com/scala/scala/blob/4905801fc161300ba20bae4f7adf045b1698e831/src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala#L47) for instance

**Comment by eed3si9n** [comment]
I noticed that we're missing this as well. Here's my PR for this - https://github.com/tree-sitter/tree-sitter-scala/pull/266
