### ISSUE TITLE
Non-standard string interpolation results in ERROR

### ISSUE THREAD

**Issue by domaspoliakas** [tree-sitter/tree-sitter-scala#316]
### Commit of tree-sitter-scala you tested this on

cda0de8a038b0e4ad79a97f7aa281250fcf88560

### A code sample showing the error

```scala
fr"hek"
```

### Show the error node

(interpolated_string_expression) ; [1:1 - 7]
 interpolator: (identifier) ; [1:1 - 2]
 (interpolated_string) ; [1:3 - 7]
  (ERROR) ; [1:3 - 7]
   (keyword_with) ; [1:3 - 2]
   (identifier) ; [1:3 - 7]

### What do you expect the tree to look like

(interpolated_string_expression) ; [1:1 - 7]
 interpolator: (identifier) ; [1:1 - 2]
 (interpolated_string) ; [1:3 - 7]

### Where are you experiencing this error?

nvim-treesitter

**Comment by KaranAhlawat** [comment]
Can't seem to reproduce this on the latest commit. Here's the output I'm getting.

```scala
fr"hek"
```

Tree:
```
(compilation_unit
 (interpolated_string_expression interpolator: (identifier) (interpolated_string)))
```

**Comment by domaspoliakas** [comment]
You're right, this seems to only happen when I apply an SQL injection query on the `fr` interpolator. Thanks!
