### ISSUE TITLE
Should we consider adding type checking to `grammar.js`?

### ISSUE THREAD

**Issue by KaranAhlawat** [tree-sitter/tree-sitter-scala#317]
So, since we have `tree-sitter-cli` defined in the `package.json`, we can actually tell language servers how to type-check the `grammar.js` file.

This does not result in an added build step.
This does result in a couple red squiggles in your editor of choice, but they can mostly be safely ignored.
And more importantly, it also provides auto completion for all the rules.

This is not a necessity or anything, just had a thought so I wanted to see if it's something that other people developing the grammar would be interested in.

**Comment by susliko** [comment]
@KaranAhlawat 
Not sure  is meant by type-checking of the `grammar.js`, could you elaborate, please? 🤔

**Comment by KaranAhlawat** [comment]
It's not much, tbf. It just basically allows a language server like tsls to perform the same sort of type checking that it would on a TypeScript file, but in the JS file we have. Main benefit imo would be the completions it provides.

If you have any mismatch in what TS expects and what you provide it, those will be reported as well (although there are a few false errors).

**Comment by ckipp01** [comment]
I believe you can already get this with just using the language server that is triggered for the JS file currently no? Can you explain explicitly what you mean by "type-checking of the `gramar.js`"?

**Comment by KaranAhlawat** [comment]
Hey, sorry for disappearing. Had exams. I'll try to produce a short screen capture of what I mean sometime this week.
