### ISSUE TITLE
Support `derives` clause with traits

### ISSUE THREAD

**Issue by ghostbuster91** [tree-sitter/tree-sitter-scala#348]
### Commit of tree-sitter-scala you tested this on

70afdd5632d57dd63a960972ab25945e353a52f6

### A code sample showing the error

```scala
trait MyTrait derives A {
}
```

### Show the error node

```
trait_definition [128, 0] - [129, 1]
  name: identifier [128, 6] - [128, 16]
  ERROR [128, 17] - [128, 29]
  body: template_body [128, 30] - [129, 1]
```

### What do you expect the tree to look like

```
(trait_definition
  (identifier)
  (derives_clause
      (type_identifier))
  (template_body)
)
```

### Where are you experiencing this error?

nvim-treesitter

**Comment by eed3si9n** [comment]
@ghostbuster91 Thanks for the report!
