### ISSUE TITLE
neovim becomes extremely sluggish after a while

### ISSUE THREAD

**Issue by perrin4869** [tree-sitter/tree-sitter-scala#36]
I haven't been able to reliably reproduce this, but it does happen without fail.
When starting neovim and doing some scala work, everything goes butter smooth, until you open and close a few buffers...
After a while, switching between buffers becomes extremely slow, it may take 3-5 seconds to switch.
I initially suspected it might have something to do with the LSP, but it turns out that it was tree-sitter:

https://github.com/perrin4869/dotfiles/blob/76893c550453a5a8ab46ce6a25685cc9c1d87ca0/home/.config/nvim/lua/treesitter.lua#L24

Disabling `scala` highlighting fixed the issue for me.
My whole neovim config is in my dotfiles repo above.

**Comment by maxbrunsfeld** [comment]
Can you open this issue on Neovim or nvim tree-sitter?

This repo would only be the right place for this issue if you could isolate the slowness to the tree-sitter parser itself, or reproduce it using the tree-sitter CLI.

**Comment by perrin4869** [comment]
Ah I see. Since I could isolate this specifically to scala under neovim I thought this would be the right place, thanks!
