### ISSUE TITLE
nvim crashes with braceless "for" in Markdown

### ISSUE THREAD

**Issue by crater2150** [tree-sitter/tree-sitter-scala#365]
Seems to be a similar problem as #159 and #194. I'm not sure how to run the grammar with markdown embedding outside of neovim, so please tell me how I can provide more debug information if needed.

### Commit of tree-sitter-scala you tested this on

1b4c2fa5c55c5fd83cbb0d2f818f916aba221a42

### A code sample showing the error

Only causes crashes when inside markdown blocks. The fenced code by itself in a .scala file does not trigger a crash.
````markdown
# Test

```scala
for
  i <- 1 to 10
yield i
```
````

Nvim does not crash if either braces are added (`{` after `for` and `}` before `yield`) or if the `i <- ...` line is not indented (i.e. same indent level as `for` and `yield`)

### Show the error node

Not sure how to get the error node with nvim crashing. Trying the manual method described in `CONTRIBUTING.md` gives me `Missing script: "parse"`.

### Where are you experiencing this error?

nvim-treesitter commit: d96c216

**Comment by susliko** [comment]
Tracked down unsafe calls in out external scanner, which caused this https://github.com/tree-sitter/tree-sitter-scala/pull/368
