### ISSUE TITLE
edge-case where single-line comment eats a finishing bracket on Objects

### ISSUE THREAD

**Issue by walksanatora** [tree-sitter/tree-sitter-scala#396]
### Commit of tree-sitter-scala you tested this on

rust crate 0.21.0

### A code sample showing the error

```scala
object Test {
    //we have commento
}
```

### Show the error node

cannot find a error node as it is a edge-case
(compilation_unit (object_definition name: (identifier) body: (template_body (comment))))

it appears to "fold" the final `}` into the comment when a comment appears before end of file

### What do you expect the tree to look like

probally the same tree. (mabey a new value appears at the end)
(compilation_unit (object_definition name: (identifier) body: (template_body (comment))))

### Where are you experiencing this error?

the rust crate version

**Comment by eed3si9n** [comment]
@walksanatora 
> I was just forgetting to add a newline... (why can I not close it myself...)

Was the comment on https://github.com/tree-sitter/tree-sitter-scala/issues/384#issuecomment-2083788413 intended for this issue? If so should I close this?

**Comment by walksanatora** [comment]
yeah I put it on the wrong issue

**Comment by walksanatora** [comment]
(also slightly saddened that `match` statments aren't turned into a `match_expression` or smth like that with a `value: Identifier` field and some "branch" fields or smth like that, but that's just a gripe with the lib and not a bug)

**Comment by eed3si9n** [comment]
Feel free to open an issue, or send us a PR to improve match expression.
