### ISSUE TITLE
Chained functions with case on the same line get messed up

### ISSUE THREAD

**Issue by ckipp01** [tree-sitter/tree-sitter-scala#40]
During work today while using some Akka streams stuff where it's common to change a lot of methods, I found this example:

<img width="1271" alt="Screenshot 2021-10-13 at 15 44 58" src="https://user-images.githubusercontent.com/13974112/137145644-60f8f4e4-1209-44b6-883f-d4c076f18af2.png">

It looks like it chokes right at the `.collect { case`. Note that this doesn't happen on a single collect, but I'm assuming it has something to do with a bunch of chained methods and then this. Note that in this scenario if you drop the `case` down to the next line it parses fine. here is a minimal production:

```scala
object Test {
  Flow[Thing]
    .mapAsync(1) { blah =>
      repository.findthings(blah).map((a, _))
    }
    .collect { case (a, Some(b)) =>
      (a, b)
    }
    .flatMapConcat { case (a, b) =>
      repository.queryTHing().map((a, b, _))
    }
}
```

**Comment by stumash** [comment]
I think this is fixed

**Comment by ckipp01** [comment]
> I think this is fixed

Just double checked this example and yes, looks like it is. Thanks for the head up!
