### ISSUE TITLE
Highlighting fails for string literal unions

### ISSUE THREAD

**Issue by spaceunifyfifty** [tree-sitter/tree-sitter-scala#406]
### Commit of tree-sitter-scala you tested this on

45b5ba0e749a8477a8fd2666f082f352859bdc3c

### A code sample showing the error

Syntax highlighting for string literal union types fails under multiple circumstances. I first noticed this on Scastie (issue posted [here](https://github.com/scalacenter/scastie/issues/1088)), but also experience it on Zed.

Here is a screenshot of the failing cases I've found so far

<img width="1060" alt="image" src="https://github.com/user-attachments/assets/f31985df-821e-4aee-b270-734a0eabd7cd">

```scala
// works!
type test1 = "a" | "b"
```
```scala
// fails after two elements
type test2 = "a" | "b" | "c"
```
```scala
// breaks from tokens on next line
type test3 = "a" | "b"
// like this comment
```
```scala
type test4 = "a" | "b"
type test4_ = "x" | "y"
// breaks subsequent lines as well
```
```scala
// fails for parameter types
def test5(x: "a" | "b") = ???
```
```scala
// fails for return types
def test6(): "a" | "b" = ???
```

Zed version: 0.142.6
Zed Scala extension version: 0.0.3

### Show the error node

will add later if I have time to figure out. I am not familiar with how tree-sitters work.

### Where are you experiencing this error?

Zed, Scastie

**Comment by susliko** [comment]
@spaceunifyfifty Thanks for reporting!
