### ISSUE TITLE
Not recognizing the @Inject syntax

### ISSUE THREAD

**Issue by phumke** [tree-sitter/tree-sitter-scala#41]
Hi Tree-Sitter-Scala,

When parsing the following class the private val lines are not showing up in the tree:
```
class MyClass @Inject()(injectedVar1: Type1, injectedVar2: Type2) {
  private val VARIABLE = "blah"
  private val VARIABLE2 = "blah2"
}
```

However removing the `@Inject` parses without an issue:
```
class MyClass {
  private val VARIABLE = "blah"
  private val VARIABLE2 = "blah2"
}
```

**Comment by eed3si9n** [comment]
Here's my PR for this - https://github.com/tree-sitter/tree-sitter-scala/pull/143
