### ISSUE TITLE
Scala 3 syntax support?

### ISSUE THREAD

**Issue by peterstorm** [tree-sitter/tree-sitter-scala#43]
Hello! 

Just wondering if Scala 3 syntax support was in the works?

Specifically the braceless syntax.

Thank you for your work!

**Comment by eed3si9n** [comment]
Here's my PR for the optional braces support - #62

**Comment by ckipp01** [comment]
Now that #62 has been merged in we'll start to focus on individual parts of the missing grammar. So in short, the answer to your question @peterstorm is yea, it's in the works 👍🏼 .

Please do report issues as we're actively working on stuff.
