### ISSUE TITLE
ERROR on indented expressions that aren't really indented

### ISSUE THREAD

**Issue by KaranAhlawat** [tree-sitter/tree-sitter-scala#433]
### Commit of tree-sitter-scala you tested this on

v0.23.2

### A code sample showing the error

```scala
def hi =
    e match
    case 1 => "Ok"
    case _ => "Also Ok"
```

### Show the error node

```
(function_definition name: def (identifier) body: =
 (indented_cases
  (ERROR (identifier) match)
  (case_clause case pattern: (integer_literal) body: => (string))
  (case_clause case
   pattern: (wildcard _)
   body: => (string))))
```

### What do you expect the tree to look like

```
(function_definition name: def (identifier) body: =
 (indented_block
  (match_expression value: (identifier) match
   body: 
    (indented_cases
     (case_clause case pattern: (integer_literal) body: => (string))
     (case_clause case
      pattern: (wildcard _)
      body: => (string))))))
```

### Where are you experiencing this error?

Emacs

**Comment by KaranAhlawat** [comment]
Not really sure if this is an error or expected behavior, since technically the cases *aren't* indented in relation to the match expression, but this is valid Scala code

**Comment by eed3si9n** [comment]
Thanks for the report! If it's a valid Scala code, then it's tree-sitter-scala's bug.

**Comment by SethTisue** [comment]
I kind of hate that it's valid Scala code, but it is.

**Comment by susliko** [comment]
Looks like a duplicate of https://github.com/tree-sitter/tree-sitter-scala/issues/264
