### ISSUE TITLE
val declaration parsed as postfix expression at start of anonymous lambda

### ISSUE THREAD

**Issue by stumash** [tree-sitter/tree-sitter-scala#47]
notice the `val` is not highlighted
![image](https://user-images.githubusercontent.com/13181078/156033235-64e6d460-5c18-4f28-8ca2-45642d4981d7.png)

Here's what tree-sitter thinks the code is
![image](https://user-images.githubusercontent.com/13181078/156033333-506affe5-dcb5-49c0-b45e-83a5ad04fcc4.png)

notice that it thinks that the `left`-hand side of the `assignment_expression` is a `postfix_expression` instead of that the entire `assignment_expression` is actually just a `val_definition`.

This issue appears to go away if I simply precede the `val_definition` with any line of code
![image](https://user-images.githubusercontent.com/13181078/156034023-aaa5cd7f-7fbd-49b8-beee-c544d18eeae0.png)

However, even though the highlighting is correct, tree-sitter no longer thinks the now-correctly-identified `val_definition` _is even within the `lambda_expression` at all!_
![image](https://user-images.githubusercontent.com/13181078/156034221-250ee082-7e4b-45f2-92a2-8ba291663ad1.png)

**Comment by StefanosTouf** [comment]
i have the same issue, is there any way to just force treesitter to always highlight `val` the same?

**Comment by stumash** [comment]
> i have the same issue, is there any way to just force treesitter to always highlight `val` the same?

no, at last not without submitting a PR to this repo and just directly making a change to the parser.

I haven't had time recently to do it, feel free to take a crack at it if you also know about parsers and whatnot

**Comment by StefanosTouf** [comment]
> no, at last not without submitting a PR to this repo and just directly making a change to the parser.

I dont know much about parsers so i dont think i can contribute any time soon :p

**Comment by StefanosTouf** [comment]
This is a non ideal solution but it seems like its fine for now, so ill post it here for anyone interested.
```
additional_vim_regex_highlighting = {"scala"}
```
