### ISSUE TITLE
Release and tag a new version

### ISSUE THREAD

**Issue by jirutka** [tree-sitter/tree-sitter-scala#49]
Can you please release a new version? The latest one (v0.19.0) doesn’t work with modern nvim-treesitter.

I’m maintainer of the [tree-sitter-scala](https://pkgs.alpinelinux.org/packages?name=tree-sitter-scala) package in Alpine Linux and I had to update the package to the latest revision in the master branch, instead of using the tagged release, which is not optimal.

**Comment by Will-Sommers** [comment]
This would be super helpful for us too!

**Comment by eed3si9n** [comment]
@ckipp01 Should we bump the version number in package.json and add a new tag for 0.19.1?

**Comment by ckipp01** [comment]
> Can you please release a new version? The latest one (v0.19.0) doesn’t work with modern nvim-treesitter.

Hey @jirutka just to make sure I understand the actual issue, could you expand a bit more on this? When using `nvim-treesitter` it should actual pull the latest revision [in the lock file](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/lockfile.json#L336). Where does the version actually come into play and cause an issue? Just asking to better understand myself.

> @ckipp01 Should we bump the version number in package.json and add a new tag for 0.19.1?

Sure!
