### ISSUE TITLE
`with` after extending abstract class with Param

### ISSUE THREAD

**Issue by domaspoliakas** [tree-sitter/tree-sitter-scala#56]
Hello 👋 

First time issue creator here, let me know if you need anything else from me!

The following code produces an error node:

```scala
abstract class Potato()
trait Tomato
class MyClass extends Potato() with Tomato
```

The treesitter AST shows the following:
```
class_definition [29, 0] - [29, 23]
  modifiers [29, 0] - [29, 8]
  name: identifier [29, 15] - [29, 21]
  class_parameters: class_parameters [29, 21] - [29, 23]
trait_definition [30, 0] - [30, 12]
  name: identifier [30, 6] - [30, 12]
class_definition [31, 0] - [31, 30]
  name: identifier [31, 6] - [31, 13]
  extend: extends_clause [31, 14] - [31, 30]
    type: type_identifier [31, 22] - [31, 28]
    arguments [31, 28] - [31, 30]
ERROR [31, 31] - [33, 0]
  identifier [31, 31] - [31, 35]
  identifier [31, 36] - [31, 42]
```

It seems that using `with` after extending an abstract class with parameters does not work.

EDIT: it seems that `abstract` class is not required, the same occurs with just a regular class too

**Comment by eed3si9n** [comment]
Here's my PR for this - https://github.com/tree-sitter/tree-sitter-scala/pull/139
