### ISSUE TITLE
Add maintainers?

### ISSUE THREAD

**Issue by eed3si9n** [tree-sitter/tree-sitter-scala#63]
Copying from https://github.com/tree-sitter/tree-sitter-scala/pull/61#issuecomment-1351605018

Looking at the open and closed prs on this repo it's been a bit of a struggle to get reviews and get changes merged in. There's an uptick in usage right now from the Scala community on this repo, and we'd hope to not lose that.

Are you open to having more maintainers of the repo? We'd (@ckipp01 and @eed3si9n) be happy to step up and play larger roles in reviewing and getting things across the board here if that's a possibility. Thanks!

/cc @aryx

**Comment by damieng** [comment]
If I don't see any objections to this I'm going to make @eed3si9n and @ckipp01 maintainers to this repo given their interest and history of successful contributions.

**Comment by eed3si9n** [comment]
Thanks @damieng!

**Comment by damieng** [comment]
Invites have been sent. Closing issue but feel free to continue discussion here if needed.

**Comment by ckipp01** [comment]
Thanks so much @damieng!!

**Comment by sideeffffect** [comment]
Here are some PRs that can be salvaged/resuscitated now:

 * https://github.com/tree-sitter/tree-sitter-scala/pull/46
 * https://github.com/tree-sitter/tree-sitter-scala/pull/51
 * https://github.com/tree-sitter/tree-sitter-scala/pull/45
 * https://github.com/tree-sitter/tree-sitter-scala/pull/55

/cc @keynmol @VixieTSQ

**Comment by eed3si9n** [comment]
@damieng Could you also add @keynmol to the maintainer please?

**Comment by damieng** [comment]
Invite sent.

**Comment by eed3si9n** [comment]
Thanks!

**Comment by ckipp01** [comment]
Hey @damieng, would you also be able to add @susliko as a maintainer for this repo?

**Comment by damieng** [comment]
Sent.
