### ISSUE TITLE
Investigate memory usage of parser generator

### ISSUE THREAD

**Issue by keynmol** [tree-sitter/tree-sitter-scala#97]
[We flew too close to the sun](https://github.com/tree-sitter/tree-sitter/issues/1890#issuecomment-1374577925)

Generation takes ~34GB of RAM, and that's why it silently fails on CI - NPM just swallows the SIGKILL.

I confirmed it on my machine by running the Rust binary directly.

We should see what causes such explosion of states (or whatever) and try to either fix TS itself, or rein in the grammar's appetite.

**Comment by eed3si9n** [comment]
My System76 desktop from 2014 (with 32GB RAM) used to be able to generate `src/parser.c` until yesterday, but post-opaque type or enum, it seems like it has lost the ability to do so as well. I am glad I Newegg'ed when you shared us the magical 34GB number.

**Comment by keynmol** [comment]
Didn't you have the same issue on your Using clauses PR? Perhaps less memory, but already above the 8G GitHub runners can afford


The inline PR is likely to get much worse, so keep that Newegg tab open

**Comment by eed3si9n** [comment]
```
$ git co f504a9a63b0310c16418b70a6d2d65f1df8e8c5b
....

HEAD is now at f504a9a Merge pull request #93 from eed3si9n/wip/bump_score
$ /usr/bin/time -f "%M" node_modules/.bin/tree-sitter generate
27371636
```

so earlier today the memory requirement was 27GB.

**Comment by eed3si9n** [comment]
Here's a PR that brings down the memory usage to 11GB - https://github.com/tree-sitter/tree-sitter-scala/pull/102
